 "use client";
import Link from "next/link";import{useEffect,useMemo,useState}from"react";import type{CartItem,Product}from"@/store/types";import{Button,Card,Modal,Toast}from"./ui-kit";
export default function ShopClient(){const[p,setP]=useState<Product[]>([]),[cart,setCart]=useState<CartItem[]>([]),[q,setQ]=useState(""),[cat,setCat]=useState("all"),[load,setLoad]=useState(true),[err,setErr]=useState(""),[toast,setToast]=useState(""),[open,setOpen]=useState(false);
useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("luma-cart")||"[]"))}catch{}},[]);useEffect(()=>{localStorage.setItem("luma-cart",JSON.stringify(cart))},[cart]);useEffect(()=>{fetch("https://fakestoreapi.com/products").then(r=>{if(!r.ok)throw Error();return r.json()}).then(setP).catch(()=>setErr("Products could not be loaded.")).finally(()=>setLoad(false))},[]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2000);return()=>clearTimeout(t)}},[toast]);
const cats=useMemo(()=>["all",...new Set(p.map(x=>x.category))],[p]);const shown=useMemo(()=>p.filter(x=>(cat==="all"||x.category===cat)&&x.title.toLowerCase().includes(q.toLowerCase())),[p,cat,q]);const count=cart.reduce((s,x)=>s+x.quantity,0),total=cart.reduce((s,x)=>s+x.price*x.quantity,0);
function add(x:Product){setCart(c=>{const e=c.find(i=>i.id===x.id);return e?c.map(i=>i.id===x.id?{...i,quantity:i.quantity+1}:i):[...c,{...x,quantity:1}]});setToast("Added to cart ✓")}function change(id:number,n:number){setCart(c=>c.map(i=>i.id===id?{...i,quantity:i.quantity+n}:i).filter(i=>i.quantity>0))}
return <main><section className="overflow-hidden bg-[#16213e] text-white"><div className="container-page py-16 sm:py-24"><p className="font-bold uppercase tracking-[.2em] text-[#00c2a8]">LUMA · curated essentials</p><h1 className="mt-4 max-w-3xl text-5xl font-black sm:text-7xl">Things you'll love.<span className="block text-[#ffd166]">Nothing you don't need.</span></h1><p className="mt-5 max-w-xl leading-7 text-slate-300">A complete responsive storefront with API products, search, filters, cart persistence and checkout.</p></div></section>
<section className="container-page py-8"><div className="sticky top-20 z-20 mb-8 rounded-2xl bg-white/90 p-3 shadow-lg backdrop-blur"><div className="flex flex-col gap-3 lg:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..." className="flex-1 rounded-xl bg-[#f4f1fb] px-4 py-3 outline-none"/><div className="flex gap-2 overflow-x-auto">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`rounded-xl px-4 py-2 text-sm font-bold capitalize ${cat===c?"bg-[#7c5cff] text-white":"bg-[#f4f1fb]"}`}>{c}</button>)}</div><button onClick={()=>setOpen(true)} className="rounded-xl bg-[#16213e] px-5 py-3 font-bold text-white">Cart ({count})</button></div></div>
{load?<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:8}).map((_,i)=><div key={i} className="h-96 animate-pulse rounded-3xl bg-white"/>)}</div>:err?<p className="rounded-2xl bg-red-50 p-6 text-red-600">{err}</p>:<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{shown.map(x=><Card key={x.id} className="group overflow-hidden transition-all duration-300 hover:-translate-y-2 hover:shadow-xl"><Link href={`/shop/product/${x.id}`}><div className="flex h-64 items-center justify-center bg-[#faf9ff] p-8"><img src={x.image} alt={x.title} className="max-h-full max-w-full object-contain transition duration-500 group-hover:scale-110"/></div></Link><div className="p-5"><p className="text-xs font-bold uppercase text-[#7c5cff]">{x.category}</p><h2 className="mt-2 min-h-12 font-bold">{x.title}</h2><div className="mt-4 flex items-center justify-between"><b className="text-xl">${x.price.toFixed(2)}</b><Button onClick={()=>add(x)}>Add</Button></div></div></Card>)}</div>}</section>
<Modal open={open} title="Your cart" onClose={()=>setOpen(false)}>{cart.length?<><div className="max-h-80 space-y-3 overflow-y-auto">{cart.map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl bg-[#f7f4ff] p-3"><img src={x.image} alt="" className="h-12 w-12 object-contain"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{x.title}</p><p>${(x.price*x.quantity).toFixed(2)}</p></div><button onClick={()=>change(x.id,-1)}>-</button><b>{x.quantity}</b><button onClick={()=>change(x.id,1)}>+</button></div>)}</div><div className="mt-5 flex justify-between border-t pt-4"><b>Total</b><b>${total.toFixed(2)}</b></div><Link href="/shop/checkout" className="mt-5 block"><Button className="w-full">Checkout</Button></Link></>:<p className="py-8 text-center font-bold">Your cart is empty.</p>}</Modal><Toast message={toast} show={!!toast}/></main>}
